# Numpy

NumPy(Numerical Python): Matematiksel işlemleri yapmamızı sağlayan bir kütüphanedir.

Numpy Array: ndarray, aynı veri tipinde N boyutlu bir dizi türüdür. Geleneksel Python listelerine göre daha hızlı işlem yapmamızı sağlamaktadır.

## Numpy Array Oluşturma Yöntemleri

In [93]:
data_list = [1,2,3]

In [94]:
data_list

[1, 2, 3]

In [111]:
import numpy as np

In [112]:
arr = np.array(data_list)

In [113]:
arr

array([1, 2, 3])

In [114]:
type(arr)

numpy.ndarray

In [116]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]

In [117]:
arr2 = np.array(data_list2)

In [118]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [102]:
arr

array([1, 2, 3])

In [119]:
arr[1]

2

In [120]:
arr[2]

3

In [121]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [122]:
arr2[2,2]

90

In [123]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [124]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [125]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [126]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [127]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [128]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [129]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [130]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [131]:
a = np.linspace(0,100,21) # 0 ile 100 arası değerleri 5 parçaya böler.
print(len(a))

21


In [132]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [133]:
np.eye(6) # Birim Matris Oluşturur.

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [135]:
np.random.randint(0,10) # 0(dahil) ile 10(hariç) arasında random int oluşturur.

6

In [136]:
np.random.randint(10) # 0(dahil) ile 10(hariç) arasında random int oluşturur.

5

In [137]:
np.random.randint(1,10,5) # 1(dahil) ile 10(hariç) arasında 5 değer oluşturarak 5 değer saklayan array oluşturur.

array([7, 8, 7, 2, 1])

In [138]:
np.random.rand(2,2,3) # 0 ile 1 arasında 5 float değerler oluşturur.

array([[[0.36921998, 0.95895531, 0.01065622],
        [0.01919106, 0.41088574, 0.37722211]],

       [[0.40273838, 0.98874702, 0.87994276],
        [0.19820445, 0.57028242, 0.79533257]]])

In [139]:
np.random.randn(10,2) # 0 etrafında - ve + değerlerle Gaussian Distribution'a göre değerler oluşturur.

array([[ 0.32577036,  1.03690729],
       [ 1.24127692, -0.86134794],
       [-0.74768039, -0.52020383],
       [-2.69262908,  0.45287336],
       [ 2.30530602,  1.45518937],
       [-0.81957703,  2.19771551],
       [ 0.25984579, -1.29420473],
       [-1.06629368, -0.94205172],
       [ 0.9530845 , -0.50727815],
       [-0.63500885,  0.17049141]])

In [141]:
arr = np.arange(20)

In [142]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [144]:
arr.reshape(10,2) # 5 x 5 =  25 tek boyutlu matrisi 2 boyuta çevirir.

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [145]:
arr.reshape(4,3) # 4 x 3 25'e eşit olmadığından çeviremez ve hata verir.

ValueError: cannot reshape array of size 20 into shape (4,3)

In [146]:
newArray = np.random.randint(1,100,10)

In [147]:
newArray

array([ 6, 97, 40, 10, 56, 45, 59, 15, 83, 97])

In [148]:
newArray.max()

97

In [149]:
newArray.min()

6

In [150]:
newArray.sum() # Tüm değerlerin toplamı

508

In [151]:
newArray.mean() # Ortalama Bulur 

50.8

In [152]:
newArray.argmin() # En küçük eleman 6.indekste

0

In [153]:
newArray.argmax() # En büyük eleman 7.indekste

1

## Tekrar ve Determinant Hesaplama

In [154]:
detArray =  np.random.randint(1,100,25)

In [155]:
detArray
print(detArray.size)

25


In [156]:
detArray = detArray.reshape(5,5)

In [157]:
detArray

array([[87, 22,  6,  9, 26],
       [68, 17, 42,  4, 17],
       [ 7, 74,  8, 26, 61],
       [ 8, 99, 62, 94, 93],
       [89, 76, 57, 84, 37]])

In [158]:
np.linalg.det(detArray)

658653920.0

In [159]:
round(np.linalg.det(detArray))

658653920

In [160]:
detArray2 = np.array([[1,2],[3,4]])

In [161]:
detArray2

array([[1, 2],
       [3, 4]])

In [162]:
np.linalg.det(detArray2)

-2.0000000000000004