## Numpy Arraylerinin Temel Operasyonları


In [1]:
import numpy as np

In [2]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([2,3,4,5,6])

In [3]:
arr1

array([10, 20, 30, 40, 50])

In [4]:
arr2

array([2, 3, 4, 5, 6])

In [5]:
arr1 + arr2

array([12, 23, 34, 45, 56])

In [6]:
arr1 * arr2  # Inner Product(İç Çarpım)

array([ 20,  60, 120, 200, 300])

In [7]:
arr1 + 10

array([20, 30, 40, 50, 60])

In [8]:
arr1 - 10

array([ 0, 10, 20, 30, 40])

In [9]:
arr2 - 2

array([0, 1, 2, 3, 4])

In [11]:
arr1

array([10, 20, 30, 40, 50])

In [12]:
arr1 / 3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [14]:
arr2 ** 2

array([ 4,  9, 16, 25, 36])

In [15]:
arr1 = arr1 **2

In [16]:
arr1

array([ 100,  400,  900, 1600, 2500])

In [17]:
np.sqrt(arr1)

array([10., 20., 30., 40., 50.])

In [18]:
arr1.size

5

In [19]:
arr1.shape

(5,)

In [20]:
arr1 = np.arange(25)
arr1 = arr1.reshape(5,5)
arr1.shape

(5, 5)

In [21]:
arr1.dtype

dtype('int32')