## Numpy Array Indekslenmesi ve Parçalanması

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[1]

2

In [5]:
arr[2]

3

In [6]:
liste = [i for i in range(1,10)]
liste

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
liste[1:5]

[2, 3, 4, 5]

In [8]:
arr[1:3]

array([2, 3])

In [9]:
arr[1:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[0:4]

array([1, 2, 3, 4])

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[::2]

array([1, 3, 5, 7, 9])

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[0:3] = 25

In [15]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [17]:
arr = np.arange(1,10)

In [18]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr2 = arr # Aynı değerleri gösteren iki tane değişken

In [20]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr2[:3] =  25

In [22]:
arr2

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [23]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [24]:
arr = np.arange(1,10)

In [25]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arrCopy = arr.copy() # Değerler kopyalanıyor.Original array bozulmuyor.

In [27]:
arrCopy[:3] = 25

In [28]:
arrCopy

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [29]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
newArray = np.arange(1,21)

In [31]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
newArray = newArray.reshape(4,5);newArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [33]:
newArray[0,0]

1

In [34]:
newArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
newArray[:,:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [36]:
newArray[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [37]:
newArray[2]

array([11, 12, 13, 14, 15])

In [38]:
newArray[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Numpy Arraylerinin Filtrelenmesi

In [39]:
arr = np.arange(1,10)

In [40]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [42]:
boolValuesArray = arr > 5
boolValuesArray

array([False, False, False, False, False,  True,  True,  True,  True])

In [43]:
boolValuesArray

array([False, False, False, False, False,  True,  True,  True,  True])

In [43]:
arr[boolValuesArray] # True olanlar filtrelenir.

array([6, 7, 8, 9])

In [44]:
arr[arr > 5] # Daha kısa hali.

array([6, 7, 8, 9])